services:
  - type: web
    name: careconnect
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}

